In [1]:
import numpy as np

In [2]:
vector = np.arange(0,11)

In [3]:
vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Array With Array Operation

If you want to add two 1 dimensional numpy array / 11 dimensional vector by element by element basis, you will use simple plus operator.

In [4]:
vector + vector

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
# We can also do substraction
vector - vector

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
# We can also do multiplication
vector * vector

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [7]:
# We also can do scalar multiplication. Or in linear algebra world we can scale the vector
vector * 5
# Here we have scaled the original vector by 5 times

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [8]:
# We also can shift our vector from left to right by adding some scalar
vector + 2
# This shift will move the vector right to the 2 coordinates from existing coordinates

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
# We also can shift our vector from right to left by subtracting some scalar
vector - 2
# This shift will move the vector to the left 2 coordinates, from existing coordinates.

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [10]:
# In numpy if we didvide zero by zero it will not through any exception.
# But will only show some warning
vector / vector
# See the nan warning in the first index

D:\InstalledSoftware\Anaconda\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [11]:
# We also can use exponent with array.
# Here we will use vector to the power 3
vector ** 3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

# Universal Array Function

In [12]:
# If we want to square root everything in the array
np.sqrt(vector)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [13]:
# If we want to calculate the exponential of the array
np.exp(vector)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [14]:
# Find out the max value of the array
np.max(vector)

10

In [15]:
# Find out the min value of the array
np.min(vector)

0

In [16]:
vector.max()

10

In [17]:
vector.min()

0

In [18]:
np.sin(vector)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [19]:
# We can also use logarithomic of array
np.log(vector)

D:\InstalledSoftware\Anaconda\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])