# NumPy Arrays

Numpy arrays comes into two flavour. It come as one dimensional vector or two dimensional matrices. Important thing to remember is that vector or matrix has their own dimension. example: 

    # Vector1 = [2,8,8] this 3 dimensional vector. Here 2 is length, 8 is width & 8 is height. 
    # Vector2 = [5,6,4] this 3 dimensional vector. Here 5 is length, 6 is width & 4 is height. 
    # Vector3 = [3,5,2] this 3 dimensional vector. Here 3 is length, 5 is width & 2 is height. 
    2) Matrix = [
                 [2,8,8],
                 [5,6,4],
                 [3,5,2]
                 ] this is 3 by 3 matrix.
             
we could write this matrix like [Vector1,Vector2,Vector3]. Here each column vector has 3 dimension.
                 
Why do we call vector as 1 dimensional array in Numpy Array as each vector can takes infinite number of dimension?

Ans: Because we use list for making vector. That means we use one third bracket at the start or end. As we use one third bracket, hence we call vector as 1 dimensional.

Why do we call matrix as 2 dimensional array in Numpy Array as inside matrix each vector can takes infinite number of dimension?

Ans: Because we use list inside list for making Matrix. That means we use two third bracket at the start or end. As we use two third bracket, hence we call Matrix as 2 dimensional.

In [2]:
import numpy as np

In [2]:
# Create a python list
my_list = [1,5,6]

In [4]:
# Now we will cast this python list as an array
vector = np.array(my_list)

In [5]:
vector

array([1, 5, 6])

Now we will create 2 dimensional array. IN python world it is list inside list, 
But in linear algebra world it is Matrix

In [8]:
Matrix = [[1,4,6],[2,7,9],[8,3,1]]

In [9]:
np.array(Matrix)

array([[1, 4, 6],
       [2, 7, 9],
       [8, 3, 1]])

Numpy libraries built in function to create array easily

In [12]:
# Create a 1 dimensional numpay array / vector of 10 dimension
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# Other types of 1 dimensional numpy array / vector genaration in numpy
np.zeros(3)

array([0., 0., 0.])

In [16]:
# If we want 2 dimensional numpy array / Matrix
np.zeros((5,5))
# This matrix has 5 column vector. Each of the column vector has 5 dimension.
# This matrix is 5 by 5 matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

More exaple of numpy arrays built in function to create 1 or 2 dimensional array


In [19]:
# Create 4 dimensional vector / 1 dimensional numpy array
np.ones(4)

array([1., 1., 1., 1.])

In [21]:
# Create matrix consisting of 2 column vector(each having 3 dimension) / 2 dimensional numpy array
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
np.linspace(0,50,49)

array([ 0.        ,  1.04166667,  2.08333333,  3.125     ,  4.16666667,
        5.20833333,  6.25      ,  7.29166667,  8.33333333,  9.375     ,
       10.41666667, 11.45833333, 12.5       , 13.54166667, 14.58333333,
       15.625     , 16.66666667, 17.70833333, 18.75      , 19.79166667,
       20.83333333, 21.875     , 22.91666667, 23.95833333, 25.        ,
       26.04166667, 27.08333333, 28.125     , 29.16666667, 30.20833333,
       31.25      , 32.29166667, 33.33333333, 34.375     , 35.41666667,
       36.45833333, 37.5       , 38.54166667, 39.58333333, 40.625     ,
       41.66666667, 42.70833333, 43.75      , 44.79166667, 45.83333333,
       46.875     , 47.91666667, 48.95833333, 50.        ])

## Create an identity matrix using numpy

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Create an array of random numbers

In [27]:
# Create a 5 dimensional vector / 1 dimensional numpy array with 5 random number 
# selected between 0 to 1
np.random.rand(5)

array([0.72127035, 0.35081474, 0.97588765, 0.48176318, 0.79062648])

In [31]:
# Creata 5 by 5 matrix / 2 dimensional numpy array
np.random.rand(5,5)
# This matrix is consist of 5 column vector. Each column vector has 5 dimension.

array([[0.56147459, 0.59019634, 0.05171701, 0.88864307, 0.63140459],
       [0.58568368, 0.97199955, 0.92008698, 0.24077094, 0.88763923],
       [0.07616239, 0.29195596, 0.03532233, 0.9194044 , 0.44303155],
       [0.91389006, 0.58513832, 0.35995704, 0.85431706, 0.75518343],
       [0.48085017, 0.93813171, 0.2624009 , 0.77886647, 0.96486895]])

In [33]:
# See the difference it has extra "n" in the last
np.random.randn(4)

array([ 1.67635183, -1.03261094,  0.39337936,  0.38693154])

In [34]:
np.random.randn(4,4)

array([[-0.93063063,  3.3693594 , -0.15942503, -1.0381431 ],
       [ 2.34146256,  1.46713152, -0.90644317, -0.09893497],
       [ 0.51000373,  1.02094791, -1.14413533,  0.7394829 ],
       [ 0.9126437 , -0.68881341,  0.76275201,  0.67288502]])

In [38]:
# Get a random intreger between 1 to upto 100
np.random.randint(1,100)

32

In [40]:
# Get 10 random intreger between 1 to upto 100
np.random.randint(1,100,10)

array([ 3, 20,  5, 76, 36,  5, 24, 79, 89, 90])

# Reshape Numpy Array

In [3]:
# Create a 25 dimensional vector & store it into variable
array1 = np.arange(25)

In [4]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [5]:
array2 = np.random.randint(1,50,10)

In [6]:
array2

array([24, 15,  3, 20, 39,  8, 32, 38, 19, 21])

In [7]:
# Here we will convert 25 dimensional vector into 5 by 5 matrix
array1.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [10]:
# We will get an error if we cannot fill up the array with 25 item
array1.reshape((5,10))

ValueError: cannot reshape array of size 25 into shape (5,10)

## Check out Max & Min value from Array

In [13]:
# Create a random array & assign it to a variable
varRandomArray = np.random.randint(10,100,10)
# This will create an array which number would be from 10 to upto 100 & array will consist
# of 10 item.

In [14]:
varRandomArray

array([77, 46, 83, 39, 85, 68, 55, 45, 52, 29])

In [15]:
varRandomArray.max()

85

In [16]:
varRandomArray.min()

29

If we want to find out the index number of our max & min value then we will use below method

In [17]:
varRandomArray.argmax()

4

In [18]:
varRandomArray.argmin()

9

## Find Shape Of A Vector

In [24]:
# Create a 1 dimensional numpay array / vector of 25 dimension
vector = np.arange(0,25)
# This areas element will start from zero to upto 25

In [25]:
vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
# Now if we want to find the shape of the vector
vector.shape
# It will return (25,) because it is 1 dimensional numpy array / 25 dimensional vector

(25,)

In [28]:
# Now we will create a matrix reshaping this vector
Matrix = vector.reshape(5,5)

In [29]:
Matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
# Now we will check the shape of the Matrix
Matrix.shape
# It is 5 by 5 matrix / 2 dimensional numpy array

(5, 5)

In [32]:
# If i want to know the datatype of the matrix or vector
Matrix.dtype

dtype('int32')