In [1]:
import numpy as np

In [2]:
# Create a 1 dimensioanl numpy array / 11 dimensional vector
vector = np.arange(0,11)

In [3]:
vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

If we want select an elements from our vector / one dimensional numpy array we will use those method

In [4]:
# Here 5 is index 5
vector[5]
# As in index 5th position our item is also 5, so it will return 5.

5

In [5]:
# We can select from some index to some index
vector[1:5]
# It will select & return all the item starting from index 1 to upto index 5

array([1, 2, 3, 4])

In [6]:
vector[0:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
vector[5:]

array([ 5,  6,  7,  8,  9, 10])

In [8]:
# We will slice the 1 dimesional numpy array / 11 dimesional vector in the middle
vector[0:5]

array([0, 1, 2, 3, 4])

In [9]:
vector[:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

# Broadcast In Numpy Array

In [10]:
# Create a vector / 1 dimensional numpy array
vector1 = np.arange(0,20)

In [11]:
vector1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
# Now Broadcast number 100 in vector1's first 5 index
vector1[:5] = 100

In [13]:
vector1

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

# Copy Numpy Array

In [14]:
vector2 = np.arange(0,10)

In [15]:
vector2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
copiedVector2 = vector2.copy()

In [19]:
copiedVector2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# Now we will broadcast on the first 5 index
copiedVector2[:5] = 99

In [21]:
copiedVector2

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

In [22]:
# Check our original vector, whether it is intact or not
vector2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Indexing Matrix / 2d Numpy Array

In [24]:
# Create a Matrix / 2 dimensional Numpy Array
Matrix = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [25]:
Matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

There is two general format to grabbing elements from Matrix / 2d Numpy Array.                         
    1) Double Bracket Format.                                                                         
    2) Single Bracket Format.

###### Double Bracket Format.

In [26]:

# Lets say we want to grab first element "5" from our matrix.
Matrix[0][0]
# As the element 5 is in 1st row of 1st column. So we have passed [0][0]

5

In [27]:
# Lets say we want to grab first element "25" from our matrix.
Matrix[1][1]
# As the element 5 is in 2nd row of 2nd column. So we have passed [1][1]

25

In [30]:
# Lets say we want to grab first element "15" from our matrix.
Matrix[0][2]
# As the element 5 is in 1st row of 3rd column. So we have passed [0][2]

15

In [34]:
# So if we want to grab first row vector from the 3 by 3 matrix.
# We will use
Matrix[0]

array([ 5, 10, 15])

###### Single Bracket Format

In [37]:
# Lets say we want to grab first element "5" from our matrix.
Matrix[0,0]
# See we did not use two bracket. Instead we use comma

5

# Grab Sub-Matrix From Matrix

In [39]:
Matrix1 = np.array([[10,54,32],[80,90,70],[40,60,20]])

In [40]:
Matrix1

array([[10, 54, 32],
       [80, 90, 70],
       [40, 60, 20]])

In [41]:
# Lets say i want to grab top right corner of the matrix
Matrix1[:2,1:]

array([[54, 32],
       [90, 70]])

In [43]:
# Lets say i want to grab top right corner of the matrix
Matrix1[1:,1:]

array([[90, 70],
       [60, 20]])

If we want to grab first column vector from 3 by 3 Matrix1

In [47]:
col_vector_1 = Matrix1[:3,0]

In [51]:
col_vector_1

array([10, 80, 40])

In [52]:
col_vector_2 = Matrix1[:3,1:2]

In [53]:
col_vector_2

array([[54],
       [90],
       [60]])

In [54]:
col_vector_3 = Matrix1[:3,2:3]

In [55]:
col_vector_3

array([[32],
       [70],
       [20]])

# Conditional Selection